apiVersion: v1
kind: Service
metadata:
  name: {{ include "appl.fullname" . }}-postgres
  labels:
    {{- include "appl.labels" . | nindent 4 }}
    component: postgres
spec:
  ports:
    - port: 5432
      targetPort: 5432
      protocol: TCP
  selector:
    {{- include "appl.selectorLabels" . | nindent 4 }}
    component: postgres
