apiVersion: v2
name: cdr
description: A CDR Helm chart for Kubernetes
icon: https://raw.githubusercontent.com/eea/helm-charts/main/sources/cdr/logo_eionet.png
type: application
version: 0.3.42
appVersion: "6.7.3-204"
dependencies:
  - name: rn-zeoserver
    version: 0.1.9
    repository: https://valentinab25.github.io/helm-charts
    alias: zeoserver
  - name: rn-varnish
    version: 0.7.0
    repository: https://valentinab25.github.io/helm-charts
    condition: rn-varnish.enabled
    alias: varnish
  - name: rn-local-converters
    version: 0.1.6
    repository: https://valentinab25.github.io/helm-charts
    condition: rn-local-converters.enabled
    alias: local-converters
  - name: rn-clamav
    version: 0.1.8
    repository: https://valentinab25.github.io/helm-charts
    condition: rn-clamav.enabled
    alias: clamav
