apiVersion: v2
name: advisory-board-backend

type: application

version: 1.1.0

appVersion: "6.0.13-13"

description: Climate advisory backend
icon: https://raw.githubusercontent.com/eea/helm-charts/main/sources/advisory-board-backend/volto.png

home: https://github.com/eea/advisory-board-backend

keywords:
- CMS

# Remember to do helm dep up
dependencies:
  - name: postfix
    version: 3.0.2
    repository: https://eea.github.io/helm-charts
