apiVersion: v2
name: helpdesk-otrs
description: Eionet helpdesk
icon: https://raw.githubusercontent.com/eea/helm-charts/main/sources/helpdesk-otrs/otrs-icon.png

type: application

keywords:
- Tickets

# This is the chart version. This version number should be incremented each time you make changes
# to the chart and its templates, including the app version.
# Versions are expected to follow Semantic Versioning (https://semver.org/)
version: 0.5.3

# Version for the main container
appVersion: "v6.0.43-openid-06"

# Remember to do: helm dep up
dependencies:
  - name: postfix
    version: 1.1.0
    repository: https://valentinab25.github.io/helm-charts
# - name: mariadb
#   version: 13.1.3
#   repository: https://charts.bitnami.com/bitnami

  - name: haproxy
    version: 2.1.1
    repository: https://charts.bitnami.com/bitnami
    condition: haproxy.enabled
