apiVersion: v1
kind: Service
metadata:
  name: frontend
  labels:
    {{- include "appl.labels" . | nindent 4 }}
    component: volto

spec:
  type: {{ .Values.volto.serviceType | default "ClusterIP" }} 
  ports:
  - name: "3000"
    port: 3000
    targetPort: 3000
  selector:
    {{- include "appl.selectorLabels" . | nindent 4 }}
    component: volto
