apiVersion: v2
name: emrt-necd
description: Emission Review Tool for NEC Directive
icon: https://raw.githubusercontent.com/eea/helm-charts/main/sources/emrt-necd/logo_eionet.png

type: application

keywords:
- Reportnet
- Emmission

version: 1.0.1

# Version for the main container
appVersion: "plone-2.5.51"

# Remember to do helm dep up .
dependencies:
  - name: postfix
    version: 3.0.3
    repository: https://eea.github.io/helm-charts
  - name: zeoserver
    version: 0.1.0
    repository: https://eea.github.io/helm-charts
  - name: memcached
    version: 7.4.13
    repository: https://charts.bitnami.com/bitnami

