apiVersion: v2
name: projects
description: Forum Interest Groups and projects
icon: https://raw.githubusercontent.com/eea/helm-charts/main/sources/projects/logo_eionet.png

type: application

keywords:
- Eionet
- Groupware

# This is the chart version. This version number should be incremented each time you make changes
# to the chart and its templates, including the app version.
# Versions are expected to follow Semantic Versioning (https://semver.org/)
version: 0.3.1

# Version for the main container
appVersion: "projects-23.09.22"

# Remember to do helm dep up .
dependencies:
  - name: postfix
    version: 1.1.0
    repository: https://eea.github.io/helm-charts
    condition: postfix.enabled
