apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "postfix.fullname" . }}
  labels:
    {{- include "postfix.labels" . | nindent 4 }}

spec:
  replicas: {{ .Values.replicaCount }}
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
      maxSurge: 1

  selector:
    matchLabels:
      {{- include "postfix.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "postfix.selectorLabels" . | nindent 8 }}
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "postfix.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}

      containers:
      - name: postfix
        {{- if .Values.dryrun }}
        image: eaudeweb/mailtrap:2.4
        {{- else }}
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
        {{- end }}

        ports:
        - containerPort: 25
          protocol: TCP
          name: smtp
        - containerPort: 80
          protocol: TCP
          name: http

        env:
        - name: TZ
          value: "{{ .Values.timezone }}"
        {{- if .Values.dryrun }}
        - name: MT_USER
          value: {{ .Values.mailtrap.mtUser }}
        - name: MT_PASSWD
          value: {{ .Values.mailtrap.mtPasswd }}
        - name: MT_MAILBOX_LIMIT
          value: "{{ .Values.mailtrap.mtMailboxLimit }}"
        - name: MT_MESSAGE_LIMIT
          value: "{{ .Values.mailtrap.mtMessageLimit }}"
        {{- else }}
        - name: MTP_HOST
          value: {{ .Values.serverName }}
        - name: MTP_PASS
          value: "{{ .Values.mtpPass }}"
        - name: MTP_PORT
          value: "{{ .Values.mtpPort }}"
        - name: MTP_RELAY
          value: {{ .Values.mtpRelay }}
        - name: MTP_USER
          value: {{ .Values.mtpUser }}
        {{- end }}
        resources:
          {{- toYaml .Values.resources | nindent 10 }}
        securityContext:
          {{- toYaml .Values.securityContext | nindent 10 }}

        {{- if (.Values.livenessProbe) }}
        livenessProbe:
          {{- toYaml .Values.livenessProbe | nindent 10 }}
        {{- end }}
        {{- if (.Values.startupProbe) }}
        startupProbe:
          {{- toYaml .Values.startupProbe | nindent 10 }}
        {{- end }}

      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      restartPolicy: Always
