apiVersion: v2
name: datadict
description: Reportnet Data Dictionary
icon: https://raw.githubusercontent.com/eea/helm-charts/main/sources/datadict/logo_eionet.png

type: application

keywords:
- Reportnet

# This is the chart version. This version number should be incremented each time you make changes
# to the chart and its templates, including the app version.
# Versions are expected to follow Semantic Versioning (https://semver.org/)
version: 1.3.6

appVersion: "2025-02-19T1302"

# Remember to do helm dep up
dependencies:
  - name: postfix
    version: 3.0.6
    repository: https://valentinab25.github.io/helm-charts
    condition: postfix.enabled
