apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ .Release.Name }}-db
  labels:
    {{- include "appl.labels" . | nindent 4 }}
    component: database

spec:
  replicas: 1
  serviceName: mariadb
  selector:
    matchLabels:
      {{- include "appl.selectorLabels" . | nindent 6 }}
      component: database
  template:
    metadata:
      labels:
        {{- include "appl.selectorLabels" . | nindent 8 }}
        component: database
    spec:
      terminationGracePeriodSeconds: 10
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "appl.serviceAccountName" . }}

      containers:
      - name: mariadb
        image: mariadb:5.5.58
        ports:
        - containerPort: 3306
          protocol: TCP
        args:
        - mysqld
        - --user=mysql
        - --default_storage_engine=InnoDB
        - --character-set-server=utf8
        - --collation-server=utf8_general_ci
        - --init-connect=SET NAMES utf8
        - --innodb_log_file_size=256M
        - --innodb_buffer_pool_size=3GB
        - --max_allowed_packet=100M
        - --bulk_insert_buffer_size=64M
        - --query_cache_size=64M
        - --skip-character-set-client-handshake
        - --skip-host-cache
        - --wait_timeout=600
        env:
        - name: MYSQL_DATABASE
          value: "{{ .Values.database.database }}"
        - name: MYSQL_PASSWORD
          value: "{{ .Values.database.password }}"
        - name: MYSQL_ROOT_PASSWORD
          value: "{{ .Values.database.rootpw }}"
        - name: MYSQL_USER
          value: "{{ .Values.database.username }}"
        - name: TZ
          value: Europe/Copenhagen

        resources:
          {{- toYaml .Values.database.resources | nindent 10 }}

        securityContext:
          {{- toYaml .Values.database.securityContext | nindent 10 }}
        volumeMounts:
        - mountPath: /var/lib/mysql
          name: {{ .Release.Name }}-database

        livenessProbe:
          tcpSocket:
            port: 3306
          initialDelaySeconds: 15
          periodSeconds: 20

        resources:
          {{- toYaml .Values.database.resources | nindent 10 }}

      restartPolicy: Always

      {{- with .Values.database.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.database.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.database.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}

  volumeClaimTemplates:
  - metadata:
      name: {{ .Release.Name }}-database
    spec:
      accessModes:
      - ReadWriteOnce
      resources:
        requests:
          storage: 30Gi
