apiVersion: v1
kind: Service
metadata:
  name: gn46
  labels:
    {{- include "appl.labels" . | nindent 4 }}
    component: gn46
spec:
  type: ClusterIP
  ports:
  - port: 8080
    targetPort: 8080
  selector:
    {{- include "appl.selectorLabels" . | nindent 4 }}
    component: gn46
