apiVersion: v2
name: rn-varnish
description: A Reportnet2 varnish Helm chart for Kubernetes
icon: https://raw.githubusercontent.com/eea/helm-charts/main/sources/rn-varnish/varnish_logo.png
type: application
version: 0.7.0
appVersion: "9.0-1.2"
