image:
  repository: eeacms/art12-viewer
  pullPolicy: IfNotPresent
  # Overrides the image tag whose default is the chart appVersion.
  tag: "2.7.7"

imagePullSecrets: []

timezone: Europe/Copenhagen

localPdfUrlPrefix: "https://nature-art12.eionet.europa.eu/article12"
mapUrlPrefix: "https://nature-art12.eionet.europa.eu/article12"
pdfUrlPrefix: "https://cmshare.eea.europa.eu/s/Lxygobjdwdt6Xx9/download?path=/article-12-birds-directive/2008-2012-reporting/species-factsheets"

passwordReset: "https://www.eionet.europa.eu/password-reset"
bindName: art12_eu
flaskApp: "art12/app.py"
serverName: art12.eionet.europa.eu
debug: "False"
scriptName: /article12

# staticPath is used in the nginx configuration
staticPath: /article12/static

ingress:
  enabled: true
  hosts:
    - host: nature-art12.eionet.europa.eu
      paths:
        - path: /article12
          pathType: Prefix
  tls:
    - secretName: ''
      hosts:
        - nature-art12.eionet.europa.eu

resources:
  requests:
    memory: 256Mi
  limits:
    memory: 3Gi

