apiVersion: v2
name: habitatsdir
description: Expert review tool for Nature Directives reporting
icon: https://raw.githubusercontent.com/eea/helm-charts/main/sources/habitatsdir/logo.png

type: application

keywords:
- Reportnet
- Biodiversity
- Nature directives

# REMEMBER to update README.md
version: 0.4.3

# Remember to do: helm dep up
dependencies:
  - name: postfix
    version: 2.0.0
    repository: https://eea.github.io/helm-charts
    condition: postfix.enabled
