apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ .Release.Name }}-repo
  labels:
    {{- include "appl.labels" . | nindent 4 }}
    component: eggrepo
spec:
  replicas: 1
  serviceName: {{ .Release.Name }}-repo
  selector:
    matchLabels:
      {{- include "appl.selectorLabels" . | nindent 6 }}
      component: eggrepo
  template:
    metadata:
      labels:
        {{- include "appl.selectorLabels" . | nindent 8 }}
        component: eggrepo
    spec:
      terminationGracePeriodSeconds: 10
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "appl.serviceAccountName" . }}
      containers:
      - name: {{ .Release.Name }}-repo
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
        {{- with .Values.commandArgs }}
        args:
          {{- toYaml . | nindent 10 }}
        {{- end }}
        ports:
        - containerPort: 9090
          protocol: TCP
        env:
        - name: TZ
          value: "{{ .Values.timezone }}"
        securityContext:
          {{- toYaml .Values.securityContext | nindent 10 }}
        volumeMounts:
        - mountPath: /var/local/eggrepo
          name: {{ .Release.Name }}-eggrepo
        readinessProbe:
          tcpSocket:
            port: 9090
          initialDelaySeconds: 5
          periodSeconds: 20
        resources:
          {{- toYaml .Values.eggrepo.resources | nindent 10 }}
        securityContext:
          {{- toYaml .Values.eggrepo.securityContext | nindent 12 }}

        {{- if (.Values.eggrepo.livenessProbe) }}
        livenessProbe:
          {{- toYaml .Values.eggrepo.livenessProbe | nindent 10 }}
        {{- end }}

        {{- if (.Values.eggrepo.startupProbe) }}
        startupProbe:
          {{- toYaml .Values.eggrepo.startupProbe | nindent 10 }}
        {{- end }}

        {{- if (.Values.eggrepo.readinessProbe) }}
        readinessProbe:
          {{- toYaml .Values.eggrepo.readinessProbe | nindent 10 }}
        {{- end }}

      {{- with .Values.eggrepo.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.eggrepo.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.eggrepo.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      restartPolicy: Always

  volumeClaimTemplates:
  - metadata:
      name: {{ .Release.Name }}-eggrepo
    spec:
      accessModes:
      - ReadWriteOnce
      {{- if .Values.storageClassName }}
      storageClass: "{{ .Values.storageClassName }}"
      {{- end }}
      resources:
        requests:
          storage: 10Gi
