apiVersion: v2
name: advisory-board-frontend
type: application
version: 1.2.1
appVersion: "1.12.0"
description: Climate advisory frontend
icon: https://raw.githubusercontent.com/eea/helm-charts/main/sources/advisory-board-frontend/volto.png
home: https://github.com/eea/advisory-board-frontend
keywords:
  - CMS
