apiVersion: v2
name: mdr
description: A MDR Helm chart for Kubernetes
icon: https://raw.githubusercontent.com/eea/helm-charts/main/sources/mdr/logo_eionet.png

type: application

version: 0.3.10

appVersion: "3.9.1-215"

dependencies:
  - name: rn-zeoserver
    version: 0.1.6
    repository: https://eea.github.io/helm-charts
    alias: zeoserver
  - name: rn-varnish
    version: 0.1.5
    repository: https://eea.github.io/helm-charts
    condition: rn-varnish.enabled
    alias: varnish
  - name: rn-local-converters
    version: 0.1.3
    repository: https://eea.github.io/helm-charts
    condition: rn-local-converters.enabled
    alias: local-converters
